### ISSUE TITLE
How to customize EC2 disk configuration?

### ISSUE THREAD

**Issue by myzshen** [chef/knife-ec2#517]
# Version:

Chef Development Kit Version: 2.4.17
kitchen version: 1.19.2

# Environment: 

Workstation: macOS Sierra 10.12.6
Target server: Ubuntu 16.04
Cloud: AWS

# Scenario:

Change the default root disk size from 8GB to 40GB, and add an extra disk, when provisioning EC2 instance with kitchen test, 

# Steps to Reproduce:

The following block_device_mappings snippet in .kitchen.yml
platforms:
  - name: ubuntu-16.04
    driver:
      block_device_mappings:
        - device_name: /dev/sda
          ebs:
            volume_type: gp2
            volume_size: 40
            delete_on_termination: true

# Expected Result:

kitchen test passed

# Actual Result:

Failed to complete #create action: [Invalid device name /dev/sda] on default-ubuntu-1604

**Comment by dheerajd-msys** [comment]
@myzshen, Please try with `device_name: /dev/sdb` since `/dev/sda` isn't available for default-ubuntu-1604.

```
platforms:
  - name: ubuntu-16.04
    driver:
      image_id: ami-aa2ea6d0
      block_device_mappings:
        - device_name: /dev/sdb
          ebs:
            volume_type: gp2
            volume_size: 40
            delete_on_termination: true
```
**# Result :**
```
       EC2 instance <i-04fb0165676d29213> ready.
       Waiting for SSH service on ec2-54-172-211-214.compute-1.amazonaws.com:22, retrying in 3 second
       [SSH] Established
       Finished creating <default-ubuntu-1604> (0m55.59s).
-----> Kitchen is finished. (1m26.14s)
```
